### ISSUE TITLE
Haircolor not displayed

### ISSUE THREAD

**Issue by veremisia** [angelix2532/TOS-Addon#1]
Hey! 

I'm surprised no one has reported this yet. Or maybe I screwed up something? Basically what I'm saying is... When I create a male character and boot up the character simulator, no matter what haircolor I pick, hair always stays purple. Look here:

https://picload.org/image/rogddwlw/screenshot_20170110_00002.jpg

Any chance to get this fixed?

**Comment by angelixels** [comment]
Hi, I haven't checked the github so long. Just got it fixed. Please update the addon.
