### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Kotowee** [angelix2532/TOS-Addon#3]
Hi angelix,

i know you have recently fixed some bugs to be able to use on EP12 thank you for that.
here are some bugs i saw while using the addon
Female:
costume 2 not displaying
Male:
all head costume not displaying

all other functionality is working well

Thanks and Regards

**Comment by angelixels** [comment]
Hello, could you check if your hair costume is disabled in Inventory menu (F2) or not ?
This add-on also takes that into consideration.

**Comment by Kotowee** [comment]
it is disabled checking

**Comment by Kotowee** [comment]
checked after enabling all the HG it works fine now thank you for that
